# This is the secrets file to contain all private environment/runtime variables that Streamlit will use.
# Copy and paste this whole file to the 'Streamlit Secrets' section when hosting on Streamlit Cloud

# This is the fine-grained personal access token (PAT) configured in GitHub to allow the installing of private packages.
# PAT permissions can be set per repo, and only needs 'read only' access under 'Contents'
github_token = '<PUT_TOKEN_HERE>'

# Credentials for the app. Can add and change these as needed.
# The password is the hashed string of the actual password. See the streamlit-authenticator docs.
[auth]
[auth.credentials]
[auth.credentials.usernames]
[auth.credentials.usernames.<PUT_USERNAME_HERE>]
name = '<PUT_NAME_HERE>'
email = '<PUT_EMAIL_HERE>'
password = '<PUT_HASHED_PASSWORD_HERE>'

[auth.cookie]
name = '<PUT_COOKIE_NAME_HERE>'
key = '<PUT_SOME_KEY_HERE>'
expiry_days = '28'

[auth.preauthorised]
emails = {}